# image: docker:latest
image: ubuntu

services:
- docker:dind

stages:
  - registry

variables:
  CONTAINER_IMAGE: registry.gitlab.com/threebx/threebxmarketplace/nodetaskserver
  TS_SEMANTIC_VERSION: $TS_VERSION

# 
# CI/CD for Release
# 
add_to_registry:
  image: docker:latest
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  stage: registry
  only:
    - release
  script:
    - docker build --tag $CONTAINER_IMAGE:$TS_SEMANTIC_VERSION --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$TS_SEMANTIC_VERSION
    - docker push $CONTAINER_IMAGE:latest